openapi: 3.0.1
info:
  title: typescript
  description: |
    This is an supposed to be an api originally written in typescript.
    it has resouces specifically for learning tools like redis and mysql in nodejs typescript.
  version: 0.5.0
paths:
  /posts:
    $ref: "./routes/posts.yaml"
  /posts/{id}:
    $ref: "./routes/posts_id_param.yaml"
  /comments:
    $ref: "./routes/comments.yaml"
  /comments/{id}:
    $ref: "./routes/comments_id_param.yaml"
  /redis/{key}:
    $ref: "./routes/redis.yaml"
  /sql-comments:
    $ref: "./routes/sql-comments.yaml"
  /sql-comments/{id}:
    $ref: "./routes/sql-comments_id_params.yaml"
